version: "3.9"
name: clayboard-test-services
services:
  test_db:
    image: postgres:15
    restart: always
    container_name: clayboard-test-db
    ports:
      - "5436:5432"
    volumes:
      - ./db-test-init:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clayboard-test
    # https://stackoverflow.com/questions/9407442/optimise-postgresql-for-fast-testing
    command: -c fsync=off -c full_page_writes=off -c max_connections=10000
  shadow_db:
    image: postgres:15
    restart: always
    container_name: clayboard-test-shadow-db
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shadow
